#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config active_border_color	 "#c6a0f6"
bspc config focused_border_color "#c6a0f6"
bspc config normal_border_color  "#1e2030"
bspc config window_gap           7 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# autostart

killall picom
nitrogen --restore
bash ~/.config/polybar/launch.sh --blocks
exec picom &
exec thunar --daemon &
xfsettingsd &
xfce4-power-manager &
usr/bin/emacs --daemon
