#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc config active_border_color  "#c6a0f6"
bspc config focused_border_color "#c6a0f6"
bspc config normal_border_color  "#1e2030"
bspc config window_gap           7 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a Screenkey manage=off

# start tiled
bspc rule -a Emacs state=tiled

# start floating
bspc rule -a GParted state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Qbittorrent state=floating
bspc rule -a feh state=floating

# autostart desktop
killall picom 														# kill if already running
exec picom &															# execute picom
nitrogen --restore 												# random wallpaper
bash ~/.config/polybar/launch.sh --blocks # launch polybar

# mpd autostart
mpd

# other autostarts
exec thunar --daemon &
xfsettingsd &
xfce4-power-manager &
usr/bin/emacs --daemon
